### ISSUE TITLE
金融数据-AkShare

### ISSUE THREAD

**Issue by jindaxiang** [jobbole/awesome-python-cn#74]
[金融数据-AkShare](https://github.com/jindaxiang/akshare) 基于 Python 的开源金融数据接口, 可以作为 TuShare 的一个补充

**Comment by henryspace2008** [comment]
牛！谢谢

发自我的iPhone

**Comment by henryspace2008** [comment]
牛，这是纯python么？

发自我的iPhone

**Comment by jindaxiang** [comment]
> 牛，这是纯python么？ 发自我的iPhone
> […](#)
> 在 2019年11月4日，下午9:25，Albert King ***@***.***> 写道： ﻿ 金融数据-AkShare 基于 Python 的开源金融数据接口, 可以作为 TuShare 的一个补充 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的

**Comment by henryspace2008** [comment]
不好意思，只是import akshare就收到错误：

# Have to specify base this way to satisfy 2to3
                      ^
SyntaxError: invalid syntax

发自我的iPhone

**Comment by jindaxiang** [comment]
> 不好意思，只是import akshare就收到错误： # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone
> […](#)
> 在 2019年11月4日，下午9:39，Albert King ***@***.***> 写道： ﻿ 牛，这是纯python么？ 发自我的iPhone … 在 2019年11月4日，下午9:25，Albert King @.***> 写道： ﻿ 金融数据-AkShare 基于 Python 的开源金融数据接口, 可以作为 TuShare 的一个补充 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 是的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

目前是基于 conda 创建python3.7.3虚拟环境后安装，没有出现这个错误提示，能提供下详细的错误提示吗？

**Comment by henryspace2008** [comment]
抱歉，打扰了：

Traceback (most recent call last):
  File "iCloud/Finance/finance.py", line 1, in <module>
    import akshare as ak
  File "Documents/modules/akshare/__init__.py", line 263, in <module>
    from akshare.stock.hk_stock_sina import (get_hk_stock_hist_data,
  File "Documents/modules/akshare/stock/hk_stock_sina.py", line 10, in <module>
    import demjson
  File "Documents/modules/demjson.py", line 645
    class json_int( (1L).__class__ ):    # Have to specify base this way to satisfy 2to3
                      ^
SyntaxError: invalid syntax



发自我的iPhone

**Comment by jindaxiang** [comment]
> 抱歉，打扰了： Traceback (most recent call last): File "iCloud/Finance/finance.py", line 1, in <module> import akshare as ak File "Documents/modules/akshare/__init__.py", line 263, in <module> from akshare.stock.hk_stock_sina import (get_hk_stock_hist_data, File "Documents/modules/akshare/stock/hk_stock_sina.py", line 10, in <module> import demjson File "Documents/modules/demjson.py", line 645 class json_int( (1L).__class__ ): # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone
> […](#)
> 在 2019年11月4日，下午11:02，Albert King ***@***.***> 写道： ﻿ 不好意思，只是import akshare就收到错误： # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone … 在 2019年11月4日，下午9:39，Albert King @.> 写道： ﻿ 牛，这是纯python么？ 发自我的iPhone … 在 2019年11月4日，下午9:25，Albert King @.> 写道： ﻿ 金融数据-AkShare 基于 Python 的开源金融数据接口, 可以作为 TuShare 的一个补充 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 是的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 目前是基于 conda 创建python3.7.3虚拟环境后安装，没有出现这个错误提示，能提供下详细的错误提示吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

方便再发下调用的函数代码吗？我这边测试了 get_hk_stock_hist_data 接口是没问题的或者使用虚拟环境

**Comment by henryspace2008** [comment]
就写了一行：

import akshare as ak
current_data_df =ak.get_hk_stock_current()
print(current_data_df)

在手机上运行的，python 3.8，好像是demjson卡住了。

发自我的iPhone

**Comment by jindaxiang** [comment]
> 就写了一行： import akshare as ak current_data_df =ak.get_hk_stock_current() print(current_data_df) 在手机上运行的，python 3.8，好像是demjson卡住了。 发自我的iPhone
> […](#)
> 在 2019年11月4日，下午11:23，Albert King ***@***.***> 写道： ﻿ 抱歉，打扰了： Traceback (most recent call last): File "iCloud/Finance/finance.py", line 1, in import akshare as ak File "Documents/modules/akshare/init.py", line 263, in from akshare.stock.hk_stock_sina import (get_hk_stock_hist_data, File "Documents/modules/akshare/stock/hk_stock_sina.py", line 10, in import demjson File "Documents/modules/demjson.py", line 645 class json_int( (1L).class ): # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone … 在 2019年11月4日，下午11:02，Albert King @.***> 写道： ﻿ 不好意思，只是import akshare就收到错误： # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone … 在 2019年11月4日，下午9:39，Albert King @.> 写道： ﻿ 牛，这是纯python么？ 发自我的iPhone … 在 2019年11月4日，下午9:25，Albert King @.> 写道： ﻿ 金融数据-AkShare 基于 Python 的开源金融数据接口, 可以作为 TuShare 的一个补充 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 是的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 目前是基于 conda 创建python3.7.3虚拟环境后安装，没有出现这个错误提示，能提供下详细的错误提示吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 方便再发下调用的函数代码吗？我这边测试了 get_hk_stock_hist_data 接口是没问题的或者使用虚拟环境 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

python3.8 有可能报错，有些package可能还不支持python3.8，demjson 用的比较多，很多是不规则的json数据，暂时还不能移除这个package

**Comment by henryspace2008** [comment]
谢谢，没事，台式机上运行是没问题的。

发自我的iPhone

**Comment by jindaxiang** [comment]
> 谢谢，没事，台式机上运行是没问题的。 发自我的iPhone
> […](#)
> 在 2019年11月4日，下午11:32，Albert King ***@***.***> 写道： ﻿ 就写了一行： import akshare as ak current_data_df =ak.get_hk_stock_current() print(current_data_df) 在手机上运行的，python 3.8，好像是demjson卡住了。 发自我的iPhone … 在 2019年11月4日，下午11:23，Albert King @.> 写道： ﻿ 抱歉，打扰了： Traceback (most recent call last): File "iCloud/Finance/finance.py", line 1, in import akshare as ak File "Documents/modules/akshare/init.py", line 263, in from akshare.stock.hk_stock_sina import (get_hk_stock_hist_data, File "Documents/modules/akshare/stock/hk_stock_sina.py", line 10, in import demjson File "Documents/modules/demjson.py", line 645 class json_int( (1L).class ): # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone … 在 2019年11月4日，下午11:02，Albert King @.> 写道： ﻿ 不好意思，只是import akshare就收到错误： # Have to specify base this way to satisfy 2to3 ^ SyntaxError: invalid syntax 发自我的iPhone … 在 2019年11月4日，下午9:39，Albert King @.> 写道： ﻿ 牛，这是纯python么？ 发自我的iPhone … 在 2019年11月4日，下午9:25，Albert King @.> 写道： ﻿ 金融数据-AkShare 基于 Python 的开源金融数据接口, 可以作为 TuShare 的一个补充 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 是的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 目前是基于 conda 创建python3.7.3虚拟环境后安装，没有出现这个错误提示，能提供下详细的错误提示吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 方便再发下调用的函数代码吗？我这边测试了 get_hk_stock_hist_data 接口是没问题的或者使用虚拟环境 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. python3.8 有可能报错，有些package可能还不支持python3.8，demjson 用的比较多，很多是不规则的json数据，暂时还不能移除这个package — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，感谢支持

**Comment by henryspace2008** [comment]
打扰了，import akshare 出错，发现是调用demjson引起的。出现如下错误，能帮分析下么？

Traceback (most recent call last):
  File "iCloud/Finance/finance.py", line 1, in <module>
    import demjson
  File "Documents/modules/demjson.py", line 645
    class json_int( (1L).__class__ ):    # Have to specify base this way to satisfy 2to3
                      ^
SyntaxError: invalid syntax

发自我的iPhone

**Comment by henryspace2008** [comment]
麻烦，能看看错误在哪儿么？只是引用akshare 后就报下面错误，好像是demjson引起的。
Traceback (most recent call last):
  File "iCloud/Finance/finance.py", line 1, in <module>
    import demjson
  File "Documents/modules/demjson.py", line 645
    class json_int( (1L).__class__ ):    # Have to specify base this way to satisfy 2to3
                      ^
SyntaxError: invalid syntax

**Comment by jindaxiang** [comment]
这个问题跟之前感觉是一样的，用Python3.7.3 应该没有问题的
